version: '3.8'

volumes:
  strapi_data:
    driver: local
  strapi-uploads:
    driver: local

networks:
  strapi-network:
    name: strapi-network
    driver: bridge

services:
  strapi:
    container_name: strapi-app
    platform: linux/amd64
    build: 
      context: .
      target: production
    image: strapi-blog:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=/opt/app/data/data.db
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-1337}
    volumes:
      - ./public/uploads:/opt/app/public/uploads
      - strapi_data:/opt/app/data
      - strapi-uploads:/opt/app/public/uploads
    ports:
      - "${PORT:-1337}:1337"
    networks:
      - strapi-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s