name: Auto Deploy

on:
  push:
    branches:
      - main  # deploy only when main branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger SSH deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /root/strapi
            git fetch --all
            git reset --hard origin/main
            ./deploy.sh
