name: Auto Deploy

on:
  push:
    branches:
      - main  # deploy only when main branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger SSH deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          timeout: 600              # extend to 10 mins (avoid "Run Command Timeout")
          command_timeout: 20m      # give Docker build up to 20 mins if needed
          script_stop: true         # fail fast if any script step fails
          script: |
            cd /root/strapi
            git fetch
